package com.mahendracandi.hibernatemaven.model;
// Generated Mar 21, 2018 9:06:48 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Buku generated by hbm2java
 */
@Entity
@Table(name="buku"
    ,catalog="dbbuku"
)
public class Buku  implements java.io.Serializable {


     private String kdbuku;
     private Penerbit penerbit;
     private Pengarang pengarang;
     private String judul;
     private int halaman;
     private Date tahunTerbit;
     private String deskripsi;

    public Buku() {
    }

    public Buku(String kdbuku, Penerbit penerbit, Pengarang pengarang, String judul, int halaman, Date tahunTerbit, String deskripsi) {
       this.kdbuku = kdbuku;
       this.penerbit = penerbit;
       this.pengarang = pengarang;
       this.judul = judul;
       this.halaman = halaman;
       this.tahunTerbit = tahunTerbit;
       this.deskripsi = deskripsi;
    }
   
     @Id 

    
    @Column(name="kdbuku", unique=true, nullable=false, length=4)
    public String getKdbuku() {
        return this.kdbuku;
    }
    
    public void setKdbuku(String kdbuku) {
        this.kdbuku = kdbuku;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="kdpenerbit", nullable=false)
    public Penerbit getPenerbit() {
        return this.penerbit;
    }
    
    public void setPenerbit(Penerbit penerbit) {
        this.penerbit = penerbit;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idpengarang", nullable=false)
    public Pengarang getPengarang() {
        return this.pengarang;
    }
    
    public void setPengarang(Pengarang pengarang) {
        this.pengarang = pengarang;
    }

    
    @Column(name="judul", nullable=false, length=50)
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }

    
    @Column(name="halaman", nullable=false)
    public int getHalaman() {
        return this.halaman;
    }
    
    public void setHalaman(int halaman) {
        this.halaman = halaman;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="tahun_terbit", nullable=false, length=10)
    public Date getTahunTerbit() {
        return this.tahunTerbit;
    }
    
    public void setTahunTerbit(Date tahunTerbit) {
        this.tahunTerbit = tahunTerbit;
    }

    
    @Column(name="deskripsi", nullable=false)
    public String getDeskripsi() {
        return this.deskripsi;
    }
    
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi;
    }




}


