CREATE TABLE KARYAWAN(
	idkaryawan VARCHAR(10) NOT NULL PRIMARY KEY,
	nama VARCHAR(30) NOT NULL,
	sertifikat VARCHAR(30) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE SERTIFIKAT(
	idsertifikat INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nama VARCHAR(30) NOT NULL
)ENGINE=InnoDB;