CREATE TABLE Department(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    student VARCHAR(30) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE Student(
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(30) NOT NULL,
    department_id INT NOT NULL
)ENGINE=InnoDB;
