package com.mahendracandi.tokobaju.model;
// Generated Jan 28, 2018 8:18:07 AM by Hibernate Tools 4.3.1



/**
 * Baju generated by hbm2java
 */
public class Baju  implements java.io.Serializable {


     private String kodeBaju;
     private String merkBaju;
     private String ukuran;

    public Baju() {
    }

    public Baju(String kodeBaju, String merkBaju, String ukuran) {
       this.kodeBaju = kodeBaju;
       this.merkBaju = merkBaju;
       this.ukuran = ukuran;
    }
   
    public String getKodeBaju() {
        return this.kodeBaju;
    }
    
    public void setKodeBaju(String kodeBaju) {
        this.kodeBaju = kodeBaju;
    }
    public String getMerkBaju() {
        return this.merkBaju;
    }
    
    public void setMerkBaju(String merkBaju) {
        this.merkBaju = merkBaju;
    }
    public String getUkuran() {
        return this.ukuran;
    }
    
    public void setUkuran(String ukuran) {
        this.ukuran = ukuran;
    }




}


